### PR TITLE
Firehose handler

### PR DESCRIPTION
**Pull request by erikreppel**

### CODE REVIEW

**Comment by erikreppel** [comment]
@jaysvoboda this should be alright but wanna take a peak?

**Comment by tj** [comment]
woo this would be sweet, though I'd suggest using the regular AWS SDK (similar to https://github.com/tj/http_to_firehose/blob/master/client/client.go)

**Comment by tj** [comment]
For the logging case we'd need some form of retries / batching for the rate limiting, dropping logs is never great but this would be really awesome to have

**Comment by erikreppel** [comment]
Oops, did not mean send this PR. My bad, I meant to just send it to our fork. Definitely not ready yet, if it comes into any kind of workable shape I'll send over another!

**Comment by tj** [comment]
sounds good!

**Pull request closed without merging**
